log    =    log/$(Cluster)_$(file).log
error  =  error/$(Cluster)_$(file).err
output = output/$(Cluster)_$(file).out

universe = vanilla

executable = ./job.sh
arguments = $(file)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = Rscript.R, http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz, inputFileList, /home/groups/STAT_DSCP/group10/$(file), inputFileList

request_cpus = 1
request_memory = 6GB
request_disk = 2GB

queue file from inputFileList

