log    =    log/$(Cluster)_$(file).log
error  =  error/$(Cluster)_$(file).err
output = output/$(Cluster)_$(file).out

universe = vanilla

executable = ./plots.sh
arguments = AA.csv_predicted.csv

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = plots.R, http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz, AA.csv_predicted.csv, packages_FITSio.tar.gz

request_cpus = 1
request_memory = 2GB
request_disk = 2GB

queue
